# Site Settings
title: Dylan Spagnuolo's Blog
copyright_notice: "© 2023 Dylan Spagnuolo. All Rights Reserved."
description: "Dylan Spagnuolo's Website & Blog"
theme: minima
url: "https://dylanspagnuolo.com"

# Minima Customizations
github_url: "https://github.com/dylanspag"
linkedin_url: "https://www.linkedin.com/in/dylan-spagnuolo"
show_excerpts: true
plugins:
  - jekyll-feed

